namespace MWV
{
    public enum PageErrorCode
    {
        ERROR_TOO_MANY_REQUESTS = -15, // 0xFFFFFFF1
        ERROR_FILE_NOT_FOUND = -14, // 0xFFFFFFF2
        ERROR_FILE = -13, // 0xFFFFFFF3
        ERROR_BAD_URL = -12, // 0xFFFFFFF4
        ERROR_FAILED_SSL_HANDSHAKE = -11, // 0xFFFFFFF5
        ERROR_UNSUPPORTED_SCHEME = -10, // 0xFFFFFFF6
        ERROR_REDIRECT_LOOP = -9, // 0xFFFFFFF7
        ERROR_TIMEOUT = -8, // 0xFFFFFFF8
        ERROR_IO = -7, // 0xFFFFFFF9
        ERROR_CONNECT = -6, // 0xFFFFFFFA
        ERROR_PROXY_AUTHENTICATION = -5, // 0xFFFFFFFB
        ERROR_AUTHENTICATION = -4, // 0xFFFFFFFC
        ERROR_UNSUPPORTED_AUTH_SCHEME = -3, // 0xFFFFFFFD
        ERROR_HOST_LOOKUP = -2, // 0xFFFFFFFE
        ERROR_UNKNOWN = -1, // 0xFFFFFFFF
    }
}
